name: Npm publish pre release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to publish on the form of x.x.x-pre.x"
        required: true

jobs:
  check:
    uses: soos-io/.github/.github/workflows/npm-publish-pre-release-workflow.yml@main
    with:
      version: ${{ inputs.version }}
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
